Repository all-rit/ALL, pull requests merged in 2024-03, with the labels that each got.

#554 553 story prettier fix to only format staged files
  .husky/pre-commit
  client/.lintstagedrc.json
  server/.lintstagedrc.json
Labels: documentation, enhancement, dependencies

#528 502 Imagine 2023 Reading Page Text Resizing
  client/src/components/body/Reading/NonBulletList.jsx
  client/src/components/body/Reading/Reading.js
  client/src/components/imagine23/Main.js
  client/src/reducers/MainReducerForContext.js
Labels: Imagine 2023

#539 512 lab 7 redux conversion
  .vscode/settings.json
  client/src/components/exercise/lab7/Main.js
  client/src/components/exercise/lab7/components/Code.js
  client/src/components/exercise/lab7/components/File.js
  client/src/components/exercise/lab7/components/MessageModal.js
  client/src/components/exercise/lab7/components/Simulation.js
  client/src/components/exercise/lab7/components/data/files.js
  client/src/components/exercise/lab7/pages/AlterationActivity/AlterationQuiz.js
  client/src/components/exercise/lab7/pages/AlterationActivity/AlterationStart.js
  client/src/components/exercise/lab7/pages/ExerciseEnd.js
  client/src/components/exercise/lab7/pages/ExerciseStart.js
  client/src/components/exercise/lab7/pages/ImproveAICode/AICodeRepair.js
  client/src/components/exercise/lab7/pages/ImproveAICode/ImprovedAISimulation.js
  client/src/components/exercise/lab7/pages/Simulation/AISimulation.js
  client/src/components/exercise/lab7/pages/Simulation/BadAIExplanation.js
  client/src/components/exercise/lab7/pages/Simulation/SimulationSummary.js
  client/src/constants/lab7/index.js
  client/src/helpers/GetReducer.js
  client/src/reducers/index.js
  client/src/reducers/lab7/AppReducer.js
  client/src/reducers/lab7/ExerciseReducer.js
  client/src/reducers/lab7/Lab7Context.js
  client/src/reducers/lab7/RepairReducer.js
Labels: dependencies
